### ISSUE TITLE
cmake error: include could not find load file GrVersion

### ISSUE THREAD

**Issue by projectbugar** [daniestevez/gr-libfec#1]
//Hello! Im new to gnuradio and as I try to compile this OOT Module, ive got this error:

Checking for GNU Radio Module: RUNTIME
-- Checking for module 'gnuradio-runtime'
--   No package 'gnuradio-runtime' found
 * INCLUDES=/home/pi/prefix/include
 * LIBS=/home/pi/prefix/lib/libgnuradio-runtime.so
GNURADIO_RUNTIME_FOUND = TRUE
CMake Error at CMakeLists.txt:128 (include):
  include could not find load file:

    GrVersion

CMake Error at cmake/Modules/GrMiscUtils.cmake:143 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
Call Stack (most recent call first):
  lib/CMakeLists.txt:52 (GR_LIBRARY_FOO)

-- Using install prefix: /usr/local
-- Building for version:  / 
-- Configuring incomplete, errors occurred!
See also "/home/pi/prefix/src/gr-libfec/build/CMakeFiles/CMakeOutput.log".

// Is there anything that im missing of? ive tried to search the web and got no similar issues to mine. I do need help here..thanks!

**Comment by daniestevez** [comment]
It seems GNU Radio is not properly installed in your system and cmake can't find it.

**Comment by projectbugar** [comment]
I've installed gnuradio using pybombs and I am running Rasbian Jessie.  In this directory /home/pi/prefix/src/gnuradio/cmake/Modules, i found GrVersion.cmake, is this the file the system is failing to load?

**Comment by daniestevez** [comment]
I think you can use the environment variable `CMAKE_MODULE_PATH` to point cmake to the right location for that file.

**Comment by projectbugar** [comment]
How do I do it sir?

**Comment by daniestevez** [comment]
Probably

`CMAKE_MODULE_PATH=/home/pi/prefix/src/gnuradio/cmake/Modules cmake ..`

**Comment by projectbugar** [comment]
The error is still the same..

**Comment by projectbugar** [comment]
Ive tried to delete and clone again the Module. It works now! Thank you so much sir!
